version: 2

sources:
    - name: mn_stores
      description: This is a replica of the database
      database: raw
      schema: mnstores
      tables:
          - name: daily_sales
            description: Daily Sales Table
          - name: order_methods
            description: customer ordered methods 
          - name: products
            description: Details of Products
          - name: retailers
            description: Details of Retailers
              